[server]
maxUploadSize = 20
enableWebsocketCompression = false

[browser]
gatherUsageStats = false

[theme]
base = "light"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#1a1a1a"
